name: catchmate
description: "CatchMate – Die moderne Community-App für Angler mit Turnieren, Karten, KI-Coach, KöderTinder & mehr."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # Icons & UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1

  # Firebase Core + Dienste
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0

  # Maps & Standort
  flutter_map: ^6.1.0
  geolocator: ^11.0.0

  # State Management
  provider: ^6.1.2

  # Medien / Upload
  image_picker: ^1.1.0
  file_picker: ^8.0.0

  # Chat, Forum & UI-Komponenten
  flutter_chat_ui: ^1.6.10
  uuid: ^4.4.0

  # In-App Käufe (für Premium)
  in_app_purchase: ^3.1.9

  # Utils
  intl: ^0.19.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
