// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVlYs-OBXWWbd6S0D7pk13MpFVUtqNN0',
    appId: '1:962387224093:web:572ef2e3efba120622c8f4',
    messagingSenderId: '962387224093',
    projectId: 'catchmate-e6801',
    authDomain: 'catchmate-e6801.firebaseapp.com',
    storageBucket: 'catchmate-e6801.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnLKs4zaJh6DcmjRT7EYK-vxjwGOdSTUo',
    appId: '1:962387224093:android:e3208cf74bb460c622c8f4',
    messagingSenderId: '962387224093',
    projectId: 'catchmate-e6801',
    storageBucket: 'catchmate-e6801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-bzFNyppRi2RXCU0HrxoFTXuy8LcsOis',
    appId: '1:962387224093:ios:e5d4109d5ae9c0b622c8f4',
    messagingSenderId: '962387224093',
    projectId: 'catchmate-e6801',
    storageBucket: 'catchmate-e6801.firebasestorage.app',
    iosBundleId: 'com.example.catchmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-bzFNyppRi2RXCU0HrxoFTXuy8LcsOis',
    appId: '1:962387224093:ios:e5d4109d5ae9c0b622c8f4',
    messagingSenderId: '962387224093',
    projectId: 'catchmate-e6801',
    storageBucket: 'catchmate-e6801.firebasestorage.app',
    iosBundleId: 'com.example.catchmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfVlYs-OBXWWbd6S0D7pk13MpFVUtqNN0',
    appId: '1:962387224093:web:88459e41abc40a1a22c8f4',
    messagingSenderId: '962387224093',
    projectId: 'catchmate-e6801',
    authDomain: 'catchmate-e6801.firebaseapp.com',
    storageBucket: 'catchmate-e6801.firebasestorage.app',
  );
}
